version: "2"

services:
  conda-store-worker:
    build: conda-store-server
    depends_on:
      - "postgres"
      - "minio"
    volumes:
      - ./tests/assets/environments:/opt/environments:ro
      - ./tests/assets/conda_store_config.py:/opt/conda_store/conda_store_config.py:ro
    platform: linux/amd64
    command: ["wait-for-it", "conda-store-server:5000", "-t", "60", '--', 'conda-store-worker', '--config', '/opt/conda_store/conda_store_config.py']

  conda-store-server:
    build: conda-store-server
    depends_on:
      - "postgres"
      - "minio"
    volumes:
      - ./tests/assets/conda_store_config.py:/opt/conda_store/conda_store_config.py:ro
    platform: linux/amd64
    command: ["wait-for-it", "postgres:5432", '--', 'conda-store-server', '--config', '/opt/conda_store/conda_store_config.py']
    ports:
      - "5000:5000"

  jupyterlab:
    build: conda-store
    command: /opt/conda/envs/conda-store/bin/jupyter lab --allow-root --ip=0.0.0.0 --NotebookApp.token=''
    ports:
      - "8888:8888"

  minio:
    image: minio/minio:RELEASE.2020-11-10T21-02-24Z
    ports:
      - "9000:9000"
    entrypoint: sh
    command: -c 'mkdir -p /data/conda-store && /usr/bin/minio server /data'
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password

  postgres:
    image: postgres:13
    # TODO: need to properly fix this without this hack
    # reuse sqlalchemy connections
    command: postgres -c 'max_connections=200'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conda-store
